taxonomy_path: Data - Collection/Final/taxonomy.csv
course_path: Data - Collection/Final/courses.json
cv_path: Data - Collection/Final/resumes.json
job_path: Data - Collection/Final/jobs.json
mastery_levels_path: Data - Collection/Final/mastery_levels.json
results_path: Code/results
level_3: true #  Whether to use only the third level of the taxonomy and not the fourth  (if true: less skills)
nb_courses: 100
nb_cvs: -1 #Number of resumes to use (set to -1 to use all)
max_cv_skills: 15  # Maximum number of skills per resume
nb_jobs: 100
threshold: 0.8
k: 1
model: dqn
total_steps: 500000
eval_freq: 1000
nb_runs: 1
seed: 42
baseline : false #skip-expertise-only model (baseline)
feature:  "Usefulness-as-Rwd"  

#Purpose 1: compare skip-expertise-only model (baseline) with skip-expertise-Usefulness model 

